server:
  port: ${ADMIN_SERVICE_PORT}
  forward-headers-strategy: native

spring:
  application:
    name: borshchevyk.admin
  boot:
    admin:
      context-path: /admin
      monitor:
        period: 2s
      ui:
        public-url: "https://${DOMAIN_NAME}/admin"
        title: "Borshchevyk Monitoring"
        brand: "<img src='assets/img/icon-spring-boot-admin.svg'><span>Borshchevyk</span>"
      instance-proxy:
        enabled: true
  security:
    user:
      name: ${ADMIN_USERNAME}
      password: ${ADMIN_PASSWORD}

logging:
  level:
    web: DEBUG
    org.springframework.web.servlet.DispatcherServlet: DEBUG
  file:
    name: logs/${spring.application.name}.log

management:
  endpoints:
    web:
      exposure:
        include: "*"
