server:
  port: ${ADMIN_SERVICE_PORT:8085}
  forward-headers-strategy: framework

spring:
  application:
    name: admin-service
  boot:
    admin:
      context-path: /admin
      monitor:
        period: 2s
      ui:
        public-url: "https://borshchevik.su/admin"
        title: "Borshchevyk Monitoring"
        brand: "<img src='assets/img/icon-spring-boot-admin.svg'><span>Borshchevyk</span>"
      instance-proxy:
        enabled: true
  security:
    user:
      name: ${ADMIN_USERNAME:admin}
      password: ${ADMIN_PASSWORD:admin}
