server:
  port: ${SYNC_SERVICE_PORT}
  forward-headers-strategy: framework

spring:
  application:
    name: borshchevyk.sync
  datasource:
    url: ${SPRING_DATASOURCE_URL_SYNC}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: ${JPA_HIBERNATE_DDL_AUTO}
    database: ${JPA_DATABASE}
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS}
    consumer:
      group-id: sync-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  boot:
    admin:
      client:
        url: "${ADMIN_SERVICE_URL}"
        username: ${ADMIN_USERNAME}
        password: ${ADMIN_PASSWORD}
        instance:
          prefer-ip: true

app:
  kafka:
    topics:
      user-registered: ${KAFKA_TOPIC_USER_REGISTERED}
      user-updated: ${KAFKA_TOPIC_USER_UPDATED}
      message-created: ${KAFKA_TOPIC_MESSAGE_CREATED}
      message-deleted: ${KAFKA_TOPIC_MESSAGE_DELETED}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: true
  api-docs:
    path: /v3/api-docs

management:
  endpoints:
    web:
      exposure:
        include: "health,info,env,metrics,loggers,httpexchanges,logfile"
  endpoint:
    health:
      show-details: always

logging:
  file:
    name: logs/${spring.application.name}.log