server:
  port: ${USER_SERVICE_PORT}
  forward-headers-strategy: framework

spring:
  application:
    name: borshchevyk.user
  datasource:
    url: ${SPRING_DATASOURCE_URL_USER}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: ${JPA_HIBERNATE_DDL_AUTO}
    database: ${JPA_DATABASE}
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: user-service-group
  boot:
    admin:
      client:
        url: "${ADMIN_SERVICE_URL}"
        username: ${ADMIN_USERNAME}
        password: ${ADMIN_PASSWORD}
        instance:
          prefer-ip: true

app:
  kafka:
    topics:
      user-registered: ${KAFKA_TOPIC_USER_REGISTERED}
      user-updated: ${KAFKA_TOPIC_USER_UPDATED}
      user-deleted: ${KAFKA_TOPIC_USER_DELETED}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: true
  api-docs:
    path: /v3/api-docs

grpc:
  server:
    port: ${USER_GRPC_PORT}

management:
  endpoints:
    web:
      exposure:
        include: "health,info,env,metrics,loggers,httpexchanges,logfile"
  endpoint:
    health:
      show-details: always

logging:
  file:
    name: logs/${spring.application.name}.log