server:
  port: ${USER_SERVICE_PORT}
  forward-headers-strategy: framework

spring:
  application:
    name: ${USER_SERVICE_NAME}
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: ${JPA_HIBERNATE_DDL-AUTO}
    database: ${JPA_DATABASE}
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS}
    producer:
      key-serializer: ${KAFKA_PRODUCER_KEY_SERIALIZER}
      value-serializer: ${KAFKA_PRODUCER_VALUE_SERIALIZER}
    consumer:
      group-id: ${KAFKA_USER_GROUP_ID:user-service-group}
  boot:
    admin:
      client:
        url: "http://admin-service:${ADMIN_SERVICE_PORT:8085}/admin"
        username: ${ADMIN_USERNAME:admin}
        password: ${ADMIN_PASSWORD:admin}
        instance:
          prefer-ip: true

app:
  kafka:
    topics:
      user-registered: ${KAFKA_TOPIC_USER_REGISTERED}
      user-updated: ${KAFKA_TOPIC_USER_UPDATED}
      user-deleted: ${KAFKA_TOPIC_USER_DELETED}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: true
  api-docs:
    path: /v3/api-docs

grpc:
  server:
    port: ${GRPC_SERVER_PORT:9090}

management:
  endpoints:
    web:
      exposure:
        include: "health,info,env,metrics,loggers,httpexchanges,logfile"
  endpoint:
    health:
      show-details: always

logging:
  file:
    name: logs/${spring.application.name}.log
