server:
  port: ${CALLS_SERVICE_PORT}
  forward-headers-strategy: framework

spring:
  application:
    name: borshchevyk.calls
  datasource:
    url: ${SPRING_DATASOURCE_URL_CALLS}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: ${JPA_HIBERNATE_DDL_AUTO}
    show-sql: false
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS}
    consumer:
      group-id: calls-service-group
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  boot:
    admin:
      client:
        url: "${ADMIN_SERVICE_URL}"
        username: ${ADMIN_USERNAME}
        password: ${ADMIN_PASSWORD}
        instance:
          prefer-ip: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: true
  api-docs:
    path: /v3/api-docs

app:
  livekit:
    url: ${LIVEKIT_URL}
    api-key: ${LIVEKIT_API_KEY}
    api-secret: ${LIVEKIT_API_SECRET}
  kafka:
    topics:
      call-events: ${KAFKA_TOPIC_CALL_EVENTS}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

logging:
  file:
    name: logs/${spring.application.name}.log

grpc:
  client:
    user-service:
      address: '${GRPC_USER_SERVICE_ADDRESS}'
      negotiation-type: plaintext