server:
  port: ${AUTH_SERVICE_PORT}
  forward-headers-strategy: framework

spring:
  application:
    name: borshchevyk.auth
  datasource:
    url: ${SPRING_DATASOURCE_URL_AUTH}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: ${JPA_HIBERNATE_DDL_AUTO}
    database: ${JPA_DATABASE}
  data:
    redis:
      host: ${SPRING_REDIS_HOST}
      port: ${SPRING_REDIS_PORT}
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: auth-service-group
  boot:
    admin:
      client:
        url: "${ADMIN_SERVICE_URL}"
        username: ${ADMIN_USERNAME}
        password: ${ADMIN_PASSWORD}
        instance:
          prefer-ip: true

app:
  kafka:
    topics:
      user-registered: ${KAFKA_TOPIC_USER_REGISTERED}
      user-updated: ${KAFKA_TOPIC_USER_UPDATED}
      user-deleted: ${KAFKA_TOPIC_USER_DELETED}
  auth:
    challenge:
      ttl: ${AUTH_CHALLENGE_TTL}

grpc:
  client:
    message-service:
      address: '${GRPC_MESSAGE_SERVICE_ADDRESS}'
      negotiation-type: plaintext

jwt:
  secret: ${JWT_SECRET}
  access-expiration-ms: ${JWT_ACCESS_EXPIRATION_MS}
  refresh-expiration-ms: ${JWT_REFRESH_EXPIRATION_MS}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: true
  api-docs:
    path: /v3/api-docs

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

logging:
  file:
    name: logs/${spring.application.name}.log