spring:
  application:
    name: borshchevyk.gateway

  main:
    web-application-type: reactive

  autoconfigure:
    exclude: org.springframework.cloud.autoconfigure.LifecycleMvcEndpointAutoConfiguration

  threads:
    virtual:
      enabled: true

  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: ${AUTH_SERVICE_URL}
          predicates:
            - Path=/api/v1/auth/**

        - id: user-service
          uri: ${USER_SERVICE_URL}
          predicates:
            - Path=/api/v1/users/**, /api/v1/contacts/**
          filters:
            - JwtAuthenticationFilter

        - id: message-service-ws
          uri: ws://message-service:8083
          predicates:
            - Path=/api/v1/messages/ws-message/**
          filters:
            - StripPrefix=3

        - id: message-service
          uri: ${MESSAGE_SERVICE_URL}
          predicates:
            - Path=/api/v1/messages/**, /api/v1/chats/**
          filters:
            - JwtAuthenticationFilter

        - id: sync-service
          uri: ${SYNC_SERVICE_URL}
          predicates:
            - Path=/api/v1/sync/**
          filters:
            - JwtAuthenticationFilter

        - id: auth-service-swagger
          uri: ${AUTH_SERVICE_URL}
          predicates:
            - Path=/v3/api-docs/auth
          filters:
            - RewritePath=/v3/api-docs/auth, /v3/api-docs

        - id: user-service-swagger
          uri: ${USER_SERVICE_URL}
          predicates:
            - Path=/v3/api-docs/user
          filters:
            - RewritePath=/v3/api-docs/user, /v3/api-docs

        - id: message-service-swagger
          uri: ${MESSAGE_SERVICE_URL}
          predicates:
            - Path=/v3/api-docs/message
          filters:
            - RewritePath=/v3/api-docs/message, /v3/api-docs

        - id: sync-service-swagger
          uri: ${SYNC_SERVICE_URL}
          predicates:
            - Path=/v3/api-docs/sync
          filters:
            - RewritePath=/v3/api-docs/sync, /v3/api-docs
  boot:
    admin:
      client:
        url: "http://admin-service:8085/admin"
        username: ${ADMIN_USERNAME:admin}
        password: ${ADMIN_PASSWORD:admin}
        instance:
          prefer-ip: true

server:
  port: 8080

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: auth-service
        url: /v3/api-docs/auth
      - name: user-service
        url: /v3/api-docs/user
      - name: message-service
        url: /v3/api-docs/message
      - name: sync-service
        url: /v3/api-docs/sync

jwt:
  secret: ${JWT_SECRET}

management:
  endpoints:
    web:
      exposure:
        include: "health,info,env,metrics,loggers,httpexchanges,logfile"
  endpoint:
    health:
      show-details: always

logging:
  file:
    name: logs/${spring.application.name}.log
