server:
  port: ${MEDIA_SERVICE_PORT:8086}
  forward-headers-strategy: framework

spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  application:
    name: borshchevyk.media
  boot:
    admin:
      client:
        url: "http://admin-service:${ADMIN_SERVICE_PORT:8085}/admin"
        username: ${ADMIN_USERNAME:admin}
        password: ${ADMIN_PASSWORD:admin}
        instance:
          prefer-ip: true
  datasource:
    url: ${SPRING_DATASOURCE_URL_MEDIA:jdbc:postgresql://localhost:5432/borshchevyk_media}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: true
  api-docs:
    path: /v3/api-docs

app:
  s3:
    endpoint: ${S3_ENDPOINT:https://s3.cloud.ru}
    region: ${S3_REGION:ru-central-1}
    bucket: ${S3_BUCKET:bucket-d6b96b}
    access-key: ${S3_ACCESS_KEY:}
    secret-key: ${S3_SECRET_KEY:}
    tenant-id: ${S3_TENANT_ID:5624c512-13f2-476a-bc25-4940ba82543e}

management:
  endpoints:
    web:
      exposure:
        include: "health,info,env,metrics,loggers,httpexchanges,logfile"
  endpoint:
    health:
      show-details: always

logging:
  level:
    web: DEBUG
    org.springframework.web.servlet.DispatcherServlet: DEBUG
  file:
    name: logs/${spring.application.name}.log
