server:
  port: ${MEDIA_SERVICE_PORT}
  forward-headers-strategy: framework

spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  application:
    name: borshchevyk.media
  boot:
    admin:
      client:
        url: "${ADMIN_SERVICE_URL}"
        username: ${ADMIN_USERNAME}
        password: ${ADMIN_PASSWORD}
        instance:
          prefer-ip: true
  datasource:
    url: ${SPRING_DATASOURCE_URL_MEDIA}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: ${JPA_HIBERNATE_DDL_AUTO}
    show-sql: false

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: true
  api-docs:
    path: /v3/api-docs

app:
  s3:
    endpoint: ${S3_ENDPOINT}
    region: ${S3_REGION}
    bucket: ${S3_BUCKET}
    access-key: ${S3_ACCESS_KEY}
    secret-key: ${S3_SECRET_KEY}
    tenant-id: ${S3_TENANT_ID}

management:
  endpoints:
    web:
      exposure:
        include: "health,info,env,metrics,loggers,httpexchanges,logfile"
  endpoint:
    health:
      show-details: always

logging:
  level:
    web: DEBUG
    org.springframework.web.servlet.DispatcherServlet: DEBUG
  file:
    name: logs/${spring.application.name}.log