name: Deploy to VPS

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_SSH_HOST }}
          username: ${{ secrets.VPS_SSH_USERNAME }}
          password: ${{ secrets.VPS_SSH_PASSWORD }}
          script: |
            cd ~/borshchevyk-backend
            git pull origin dev
            echo "${{ secrets.PROD_ENV_FILE }}" > .env
            
            # Устанавливаем Maven на сервер, если он еще не установлен
            if ! command -v mvn &> /dev/null; then
              sudo apt-get update
              sudo apt-get install -y maven
            fi
            
            # Собираем каждый микросервис отдельно
            mvn -f borshchevyk.auth/pom.xml clean package -DskipTests
            mvn -f borshchevyk.gateway/pom.xml clean package -DskipTests
            mvn -f borshchevyk.message/pom.xml clean package -DskipTests
            mvn -f borshchevyk.user/pom.xml clean package -DskipTests
            
            docker-compose build
            docker-compose down
            docker-compose up -d
            docker image prune -f
